### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by shuvalov-anton** [lepture/selection.js#8]

**Comment by lepture** [comment]
You have published it!

https://www.npmjs.com/package/selection.js

**Comment by shuvalov-anton** [comment]
yep, sorry :D It because I needed to get it from npm to deploy my app. But you're maintainer. I don't wan't to update your module. And I can remove it if you want to publish and support it

**Comment by lepture** [comment]
@shuvalov-anton Add me as an owner

**Comment by shuvalov-anton** [comment]
@lepture done
